(* AUTOMATICALLY GENERATED BY codegen/main.ml *)

open Lwt.Syntax

exception BadRequest of string

let create_user (req : Dream.request) =
  let* body = Dream.body req in
  let body =
    Generated_server_types.CreateUserInput.t_of_yojson
      (Yojson.Safe.from_string body)
  in
  let* (result : Generated_server_types.CreateUserOutput.t) =
    Handlers.Server.create_user req body
  in
  result |> Generated_server_types.CreateUserOutput.yojson_of_t
  |> Yojson.Safe.to_string |> Dream.json

let users (req : Dream.request) =
  let query =
    match Generated_server_types.UsersQuery.parse_query req with
    | Ok q -> q
    | Error msg -> raise (BadRequest msg)
  in
  let* (result : Generated_server_types.UsersOutput.t) =
    Handlers.Server.users req query
  in
  result |> Generated_server_types.UsersOutput.yojson_of_t
  |> Yojson.Safe.to_string |> Dream.json

let get_user (req : Dream.request) =
  let user_id = Dream.param req "user_id" in
  let* (result : Generated_server_types.GetUserOutput.t) =
    Handlers.Server.get_user req user_id
  in
  result |> Generated_server_types.GetUserOutput.yojson_of_t
  |> Yojson.Safe.to_string |> Dream.json

let delete_user (req : Dream.request) =
  let user_id = Dream.param req "user_id" in
  let* (result : Generated_server_types.DeleteUserOutput.t) =
    Handlers.Server.delete_user req user_id
  in
  result |> Generated_server_types.DeleteUserOutput.yojson_of_t
  |> Yojson.Safe.to_string |> Dream.json

let generate_client_jwt (req : Dream.request) =
  let* body = Dream.body req in
  let body =
    Generated_server_types.GenerateClientJwtInput.t_of_yojson
      (Yojson.Safe.from_string body)
  in
  let* (result : Generated_server_types.GenerateClientJwtOutput.t) =
    Handlers.Server.generate_client_jwt req body
  in
  result |> Generated_server_types.GenerateClientJwtOutput.yojson_of_t
  |> Yojson.Safe.to_string |> Dream.json

let routes =
  [
    Dream.post "/_/users" create_user;
    Dream.get "/_/users" users;
    Dream.get "/_/user/:user_id" get_user;
    Dream.delete "/_/user/:user_id" delete_user;
    Dream.post "/_/gen-client-jwt" generate_client_jwt;
  ]
