(* AUTOMATICALLY GENERATED BY codegen/main.ml *)

open Lwt.Syntax

let conversations (req : Dream.request) =
  match Generated_client_types.ConversationsQuery.parse_query req with
  | Error msg -> Handlers.Client.bad_request msg
  | Ok query -> (
      let* (result :
             ( Generated_client_types.ConversationsOutput.t,
               Dream.response Lwt.t )
             result) =
        Handlers.Client.conversations req query
      in
      match result with
      | Ok result ->
          result |> Generated_client_types.ConversationsOutput.yojson_of_t
          |> Yojson.Safe.to_string |> Dream.json
      | Error response -> response)

let routes = [ Dream.get "/conversations" conversations ]
