let gen_typescript_bindings () =
  let ts_bindings =
    Gen_endpoints.Gen_ts_bindings.gen_routes ~type_namespace:""
      Endpoints.endpoints
  in
  let ts_types_result =
    [
      Gen_endpoints.Gen_ts_bindings.gen_types ~type_namespace:"" ~t:Types.t
        ~it:Types.it ~ot:Types.ot;
    ]
    @ [ "// ENDPOINTS"; ts_bindings ]
  in
  let oc = open_out "typescript_bindings/types.ts" in
  Printf.fprintf oc "/* AUTOMATICALLY GENERATED BY codegen/main.ml */\n\n%s\n"
    (String.concat "\n\n" ts_types_result);
  close_out oc

let gen_ocaml_endpoints () =
  let ocaml_types =
    Gen_endpoints.Gen_ocaml_endpoints.gen_types ~type_namespace:"" ~t:Types.t
      ~it:Types.it ~ot:Types.ot Endpoints.endpoints
  in
  let ocaml_endpoints =
    Gen_endpoints.Gen_ocaml_endpoints.gen_routes ~type_namespace:"Types."
      ~handler_namespace:"Handler." Endpoints.endpoints
  in

  let oc = open_out "lib/api/endpoints.ml" in
  Printf.fprintf oc "(* AUTOMATICALLY GENERATED BY codegen/main.ml *)\n\n%s"
    ocaml_endpoints;
  close_out oc;

  let oc = open_out "lib/api/types.ml" in
  Printf.fprintf oc "(* AUTOMATICALLY GENERATED BY codegen/main.ml *)\n\n%s"
    ocaml_types;
  close_out oc

let gen_documentation () =
  let docs =
    Gen_endpoints.Gen_documentation.gen_docs ~t:Types.t ~it:Types.it
      ~ot:Types.ot Endpoints.endpoints
  in

  let oc = open_out "api_documentation/README.md" in
  Printf.fprintf oc "<!-- AUTOMATICALLY GENERATED BY codegen/main.ml -->\n\n%s"
    docs;
  close_out oc

let () =
  gen_typescript_bindings ();
  gen_ocaml_endpoints ();
  gen_documentation ()
